services:
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      - db
    volumes:
      - db:/var/lib/mysql

networks:
  db:
    driver: bridge

volumes:
  db:
  